In [1]:
import numpy as np

In [8]:
myarr = np.array([[3,6,32,7]], np.int8) # if we use int8, number should not be large
# int32, int64 instead of int8

In [9]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [10]:
myarr[0,1]

6

In [12]:
myarr.shape # give shape -> row and column

(1, 4)

In [13]:
myarr.dtype # give data type

dtype('int8')

In [14]:
myarr[0,1] = 45

In [15]:
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

In [16]:
# Numpy Array creation methods
#1. Convert from list or tuple..
#2. Intrinsic numpy array creation objects ( arange , ones, zeros)
#3. Reading array from disk, either from standard or custom formats
#4. Creating array from raw bytes through the use of strings or buffers
#5. Use of special library functions (eg. random)

#1. Convert from list or tuple..

In [17]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [18]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [19]:
listarray.dtype

dtype('int64')

In [20]:
listarray.shape

(3, 3)

In [21]:
listarray.size

9

In [22]:
np.array({34,23,23}) # dtype = object is not that efficient, we use integer and float generally

array({34, 23}, dtype=object)

#2. Intrinsic numpy array creation objects ( arange , ones, zeros)

In [26]:
zeros = np.zeros((2, 5)) # 2 rows and 5 columns

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
zeros.dtype

dtype('float64')

In [30]:
rng = np.arange(15) # creates numpy array in range, 0 to 14

In [32]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
lspace = np.linspace(1,5,12) # gives 12 equally linearly space elements between range  1 to 5  *equal space in them

In [35]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [36]:
lspace = np.linspace(1,4,4)

In [37]:
lspace

array([1., 2., 3., 4.])

In [38]:
lspace = np.linspace(1,50,10)

In [39]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [40]:
lspace = np.linspace(1,5,4)

In [41]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [42]:
emp = np.empty((4,6)) # gives empty array of 4 rows and 6 columns , all elements will be random, we can assign any value to it

In [44]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [45]:
emp_like = np.empty_like(lspace) # gives empty array of same shape as lspace

In [46]:
emp_like # purana array lspace tha that array's size is copied in new array, these elements can be changed by us as we like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [47]:
ide = np.identity(45) # gives identity matrix of 45 rows and 45 columns

In [48]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [49]:
ide.shape

(45, 45)

In [50]:
arr = np.arange(99)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [53]:
arr = arr.reshape(3,33) # we get reshaped into 3 x 33

In [54]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [55]:
arr.shape

(3, 33)

In [58]:
arr =arr.ravel() # gives 1D array

In [59]:
arr.shape

(99,)

#3. Axis in Numpy

In [60]:
x = [[1,2,3],[4,5,6],[7,1,0]]


In [61]:
ar = np.array(x)

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
ar.sum(axis =0)

array([12,  8,  9])

In [65]:
ar.sum(axis =1)

array([ 6, 15,  8])

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar.T # Transpose of the array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [68]:
ar.flat # gives iterator

In [70]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [72]:
ar.ndim # gives dimension

2

In [73]:
ar.size # gives size, number of elements in array

9

In [74]:
ar.nbytes # gives total bytes consumed by array

72

In [75]:
one = np.array([1,3,4,634,2])

# Methods in Numpy Array

In [76]:
one.argmax() # gives index of maximum element

3

In [77]:
one.argmin() # gives index of minimum element

0

In [78]:
one.argsort() # gives index of sorted elements , if the array was sorted, it would look like this

array([0, 4, 1, 2, 3])

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [79]:
ar.argmin() #

8

In [81]:
ar.argmax()

6

In [83]:
ar.argmax(axis=0) # | | |

array([2, 1, 1])

In [85]:
ar.argmax(axis=1) # - - -

array([2, 2, 0])

In [87]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [89]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [91]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [94]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [96]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

# Mathematical Operations in Numpy

In [99]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [101]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [102]:
[324,34] + [34,546] # we cannot do marix operation in here

[324, 34, 34, 546]

In [105]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [106]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [103]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [107]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [108]:
ar.sum() # sum of all elements

29

In [109]:
ar.max()

7

In [110]:
ar.min()

0

In [111]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [113]:
np.where(ar>5) # gives index of elements which are greater than 5, it returns tuple of arrays

(array([1, 2]), array([2, 0]))

In [114]:
type(np.where(ar>5))

tuple

In [115]:
np.count_nonzero(ar) # gives count of non zero elements

8

In [116]:
np.nonzero(ar) # gives index of non zero elements

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [117]:
# the above is 0,0 | 0,1 | 0,2

In [118]:
ar[1,2] =0

In [119]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [120]:
# we get a tuple for each axis

# How numpy uses less space

In [121]:
import sys

In [123]:
py_ar = [0,4,55,2]

In [124]:
np_ar = np.array(py_ar)

In [126]:
sys.getsizeof(1) * len(py_ar) # size of 1 -> size of one element in the array

112

In [128]:
np_ar.itemsize * np_ar.size # itemsize -> one attribute (size of one item) X total items

32

In [130]:
np_ar.tolist()

[0, 4, 55, 2]